title: Bibarsov Timur
description: Блог ленивого программиста
author: John Smith
logo: /static/img/avatar.png
github: https://github.com/bibarsov
about: Freelance developer

baseurl: ""
url: "https://bibarsov.github.io/"

disqus_shortname: deadxperia
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
