title: Блог Бибарсова Тимура Равилевича
description: Code snippets, articles and other stuff that may be useful in my opinion
author: Bibarsov Timur
future: true
logo: /static/img/avatar.png
github: https://github.com/bibarsov
about: Software engineer
url: https://bibarsov.github.io
baseurl: ""
disqus_shortname: bibarsov-github-io
google_analytics: UA-82902217-1
share:
  twitter_username: \#
  fb_appid: 000000000000
enableTags: true
tagarray: []
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
