title: Блог ленивого программиста
description: Коды, переводы и другие полезные фичи
author: Bibarsov Timur
logo: /static/img/avatar.png
github: https://github.com/bibarsov
about: Freelance developer

baseurl: ""
url: "https://bibarsov.github.io/"

disqus_shortname: bibarsov-github-io
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
